---
- name: install vsftpd
  gather_facts: no
  hosts: all
  tasks:
  - name: install package
    package:
      name: vsftpd
  - name: run the service
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: open port
    firewalld:
      service: ftp
      state: enabled
      permanent: yes
      immediate: yes
