---
- name: myplay
  hosts: all
  tasks:
  - name: task1
    debug:
      msg: Hello word
  - name: task2
    debug:
      msg: hello task2
- name: ubuntusetting
  hosts: ubuntu
  tasks:
  - name: helo ubuntu
    debug:
      msg: Hello ubuntu
